import fs from "node:fs/promises";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { cloneApp } from "./gitService.js";
import { writePatchArtifact } from "./patchArtifactService.js";
import { appsRoot, id, nowIso, sanitizeTitle } from "../utils.js";
import type { CreateSoftwareInput, ManagedApp } from "../../shared/types.js";

const exec = promisify(execFile);

function inferTitle(request: string) {
  const words = request
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .split(/\s+/)
    .filter((word) => word.length > 2)
    .slice(0, 4);
  return sanitizeTitle(words.join("-") || "personal-software");
}

function appSource(title: string, request: string) {
  return `import React from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

function App() {
  return (
    <main className="app-shell">
      <section className="intro">
        <p>Personal Software Draft</p>
        <h1>${title}</h1>
        <span>Generated from your request</span>
      </section>
      <section className="request">
        <h2>Build Brief</h2>
        <p>${request.replace(/`/g, "'")}</p>
      </section>
    </main>
  );
}

createRoot(document.getElementById("root")!).render(<App />);
`;
}

const styles = `:root {
  color: #20242d;
  background: #f5f2ea;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

body { margin: 0; }

.app-shell {
  min-height: 100vh;
  display: grid;
  align-content: center;
  gap: 24px;
  padding: 64px;
}

.intro p {
  margin: 0 0 8px;
  color: #2f7a4f;
  font-weight: 700;
}

.intro h1 {
  margin: 0;
  max-width: 880px;
  font-size: clamp(44px, 7vw, 92px);
  line-height: 0.95;
}

.intro span {
  display: block;
  margin-top: 16px;
  color: #666b61;
}

.request {
  max-width: 780px;
  border: 1px solid #d8d3c8;
  background: #fffdf8;
  border-radius: 8px;
  padding: 24px;
}

.request h2 { margin: 0 0 10px; }
.request p { margin: 0; line-height: 1.6; }
`;

export async function createSoftwareProject(input: CreateSoftwareInput, workspaceRoot = appsRoot()): Promise<ManagedApp> {
  if (input.repoUrl?.trim()) {
    const cloned = await cloneApp({ repoUrl: input.repoUrl.trim(), title: input.title }, workspaceRoot);
    cloned.softwareRequest = input.request;
    cloned.researchUrls = input.researchUrls ?? [];
    cloned.buildStatus = "planned";
    const patchPath = await writePatchArtifact(cloned, input.request, cloned.currentBranch);
    cloned.patchArtifactPath = patchPath;
    cloned.runCommands.unshift({
      id: id("cmd"),
      label: "Run Codex build pass",
      command: `codex exec --ask-for-approval on-request --sandbox workspace-write ${JSON.stringify(
        `Implement this personalization request end to end. Keep .personal-software/PATCH.md updated with user-facing differences and implementation details: ${input.request}`
      )}`,
      cwd: cloned.localPath,
      risk: "high",
      approved: false
    });
    return cloned;
  }

  const title = sanitizeTitle(input.title || inferTitle(input.request));
  const localPath = path.join(workspaceRoot, title);
  const timestamp = nowIso();

  await fs.mkdir(path.join(localPath, "src"), { recursive: true });
  await fs.writeFile(
    path.join(localPath, "package.json"),
    JSON.stringify(
      {
        name: title,
        version: "0.1.0",
        private: true,
        type: "module",
        scripts: {
          dev: "vite --host 127.0.0.1",
          build: "vite build"
        },
        dependencies: {
          "@vitejs/plugin-react": "^5.1.1",
          vite: "^7.2.7",
          typescript: "^5.9.3",
          react: "^19.2.3",
          "react-dom": "^19.2.3"
        },
        devDependencies: {
          "@types/react": "^19.2.7",
          "@types/react-dom": "^19.2.3"
        }
      },
      null,
      2
    )
  );
  await fs.writeFile(path.join(localPath, "index.html"), '<div id="root"></div><script type="module" src="/src/App.tsx"></script>\n');
  await fs.writeFile(path.join(localPath, "src", "App.tsx"), appSource(title, input.request));
  await fs.writeFile(path.join(localPath, "src", "styles.css"), styles);
  await fs.writeFile(path.join(localPath, "README.md"), `# ${title}\n\nGenerated by Personal Software from this request:\n\n${input.request}\n`);
  await fs.writeFile(path.join(localPath, ".gitignore"), "node_modules\ndist\n.env\n.env.local\n");
  await exec("git", ["init", "-b", "main"], { cwd: localPath });

  const appRecord: ManagedApp = {
    id: id("app"),
    title,
    repoUrl: "local://blank-project",
    owner: "local",
    repo: title,
    defaultBranch: "main",
    localPath,
    currentBranch: "main",
    setupStatus: "inspected",
    env: [],
    runCommands: [
      {
        id: id("cmd"),
        label: "Run Codex build pass",
        command: `codex exec --ask-for-approval on-request --sandbox workspace-write ${JSON.stringify(
          `Implement this software request end to end. Keep .personal-software/PATCH.md updated with user-facing differences and implementation details: ${input.request}`
        )}`,
        cwd: localPath,
        risk: "high",
        approved: false
      },
      {
        id: id("cmd"),
        label: "Install dependencies",
        command: "npm install",
        cwd: localPath,
        risk: "medium",
        approved: false
      },
      {
        id: id("cmd"),
        label: "Build app",
        command: "npm run build",
        cwd: localPath,
        risk: "medium",
        approved: false
      },
      {
        id: id("cmd"),
        label: "Run dev server",
        command: "npm run dev",
        cwd: localPath,
        risk: "high",
        approved: false
      }
    ],
    createdAt: timestamp,
    updatedAt: timestamp,
    softwareRequest: input.request,
    researchUrls: input.researchUrls ?? [],
    buildStatus: "ready"
  };

  appRecord.patchArtifactPath = await writePatchArtifact(appRecord, input.request, appRecord.currentBranch);
  return appRecord;
}
